
import React, { useState } from 'react';
import { View, TextInput, Button } from 'react-native';
import { DataInputRequest, User } from '../types/Type';
import DataInputApi from '../apis/DataInputApi';

const DataInputForm: React.FC = () => {
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [address, setAddress] = useState('');

  const handleFormSubmit = async () => {
    const user: User = {
      userId: '', // This can be left empty as it will be generated by the backend
      firstName,
      lastName,
      email,
      phone,
      address,
    };

    const dataInputRequest: DataInputRequest = {
      user,
    };

    try {
      await DataInputApi.postDataInput(dataInputRequest);
      // Show success message or navigate to another screen
    } catch (error) {
      // Handle error
    }
  };

  return (
    <View>
      <TextInput
        placeholder="First Name"
        value={firstName}
        onChangeText={setFirstName}
      />
      <TextInput
        placeholder="Last Name"
        value={lastName}
        onChangeText={setLastName}
      />
      <TextInput
        placeholder="Email"
        value={email}
        onChangeText={setEmail}
      />
      <TextInput
        placeholder="Phone"
        value={phone}
        onChangeText={setPhone}
      />
      <TextInput
        placeholder="Address"
        value={address}
        onChangeText={setAddress}
      />
      <Button title="Submit" onPress={handleFormSubmit} />
    </View>
  );
};

export default DataInputForm;